# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rsolr-ext}
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Mitchell", "James Davidson", "Chris Beer", "Jason Ronallo", "Eric Lindvall", "Andreas Kemkes"]
  s.date = %q{2011-06-08}
  s.description = %q{A query/response extension lib for RSolr}
  s.email = %q{goodieboy@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "VERSION",
    "lib/mash.rb",
    "lib/rsolr-ext.rb",
    "lib/rsolr-ext/client.rb",
    "lib/rsolr-ext/doc.rb",
    "lib/rsolr-ext/model.rb",
    "lib/rsolr-ext/request.rb",
    "lib/rsolr-ext/response.rb",
    "lib/rsolr-ext/response/docs.rb",
    "lib/rsolr-ext/response/facets.rb",
    "lib/rsolr-ext/response/spelling.rb"
  ]
  s.homepage = %q{http://github.com/mwmitchell/rsolr-ext}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A query/response extension lib for RSolr}
  s.test_files = ["spec/*", "Rakefile"]

  s.add_dependency 'rsolr', ">= 1.0.1"
  s.add_development_dependency 'rake', '~> 0.9.2'
  s.add_development_dependency 'rdoc', '~> 3.9.4'
  s.add_development_dependency 'rspec', '~> 2.6.0'
  s.add_development_dependency 'rcov'
end

